name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Docker CLI
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }} ## GitHub organization or username
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2   
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: ghcr.io/feliksyasnopolski/mafia-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
          
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: |
    #     docker build . --file Dockerfile --tag mafia-backend:$(date +%s)
    #     docker build . --file Dockerfile --tag mafia-backend:latest
      